config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'boards#index'
  resources :boards, only: %i[index show create update destroy]
  resources :lists, only: %i[create update destroy]
  post 'cards/update_list', to: 'cards#update_list'
  resources :cards, only: %i[create update destroy]

  # Errors pages
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: boards
#
#  id             :BIGINT(20)     not null, primary key
#  tite           :VARCHAR(255)   not null
#  description    :TEXT
class Board < ApplicationRecord
  has_many :lists, dependent: :destroy

  validates :title, presence: true
end

app/models/card.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: cards
#
#  id             :BIGINT(20)     not null, primary key
#  tite           :VARCHAR(255)   not null
#  description    :TEXT
class Card < ApplicationRecord
  belongs_to :list

  validates :title, presence: true
end

app/models/list.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: lists
#
#  id             :BIGINT(20)     not null, primary key
#  tite           :VARCHAR(255)   not null
class List < ApplicationRecord
  belongs_to :board
  has_many :cards, dependent: :destroy

  validates :title, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Controller base
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def redirect_to_back(default = root_url)
    if request.env['HTTP_REFERER'].present? && (request.env['HTTP_REFERER'] != request.env['REQUEST_URI'])
      redirect_to request.env['HTTP_REFERER']
    else
      redirect_to default
    end
  end

  def message_redirect_type(status, type, path_redirect, controller)
    flash[status.to_sym] = (t "messages.#{status}.#{type}",
                              value: (t "controller.#{controller}"),
                              type: (t "controller.#{controller}")[-1] )
    if path_redirect == 'back'
      redirect_to_back
    else
      redirect_to path_redirect.to_sym
    end
  end
end

app/controllers/board_controller.rb
# frozen_string_literal: true

# Controller home boards
class BoardController < ApplicationController
  def index; end

  def show; end
end

app/controllers/boards_controller.rb
# frozen_string_literal: true

# Controller home boards
class BoardsController < ApplicationController
  before_action :boards, only: %i[index]
  before_action :board_params, only: %i[create update]
  before_action :board, only: %i[update destroy show]
  before_action :board, only: %i[update destroy show]
  before_action :board_index_modal, only: %i[index]
  before_action :board_show_modal, only: %i[show]
  before_action :all_lists_for_board, only: %i[show]

  def index; end

  def show; end

  def create
    @board = Board.new(@board_send)
    if @board.save
      message_redirect_type('success', 'create', 'root', 'board')
    else
      message_redirect_type('danger', 'create', 'root', 'board')
    end
  end

  def update
    if @board.update(board_params)
      message_redirect_type('success', 'update', 'board', 'board')
    else
      message_redirect_type('danger', 'update',  'board', 'board')
    end
  end

  def destroy
    if @board.destroy
      message_redirect_type('success', 'remove', 'root', 'board')
    else
      message_redirect_type('danger', 'remove', 'root', 'board')
    end
  end

  private

  def board
    @board = Board.find(params[:id])
  end

  def boards
    @boards = Board.where('true')
  end

  def board_index_modal
    @action = 'create'
    @method = 'post'
    @title = nil
    @description = nil
  end

  def board_show_modal
    @action = 'update'
    @method = 'patch'
    @title = @board.title
    @description = @board.description
    @bg = 'bg-blue'
  end

  def board_params
    @board_send = params.permit(:title, :description)
  end

  def all_lists_for_board
    @all_lists_for_board = List.where(board_id: @board)
  end
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

# Controller of the Caards
class CardsController < ApplicationController
  before_action :set_card, only: %i[update destroy]
  before_action :card_params, only: %i[create update]
  before_action :card_for_update, only: %i[update_list]

  def create
    @card = Card.new(@card_send)
    if @card.save
      message_redirect_type('success', 'create', 'back', 'card')
    else
      message_redirect_type('danger', 'create', 'back', 'card')
    end
  end

  def update
    if @card.update(@card_send)
      message_redirect_type('success', 'update', 'back', 'card')
    else
      message_redirect_type('danger', 'update', 'back', 'card')
    end
  end

  def update_list
    if @card.update(list_id: @list_id)
      redirect_to_back
    else
      message_redirect_type('danger', 'update', 'back', 'card')
    end
  end

  def destroy
    if @card.destroy
      message_redirect_type('success', 'remove', 'back', 'card')
    else
      message_redirect_type('danger', 'remove', 'back', 'card')
    end
  end

  private

  def set_card
    params[:card_id].present? ? (@card = Card.find(params[:card_id])) : (@card = Card.find(params[:card_id_del]))
  end

  def card_for_update
    @card_update = JSON.parse(params[:update_list]).with_indifferent_access
    @card = Card.find(@card_update[:card_id])
    @list_id = @card_update[:list_id]
  end

  def card_params
    @card_send = params.permit(:title, :description, :list_id)
  end
end

app/controllers/errors_controller.rb
# frozen_string_literal: true

# Controller for errors pages
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def unacceptable
    render status: 422
  end

  def internal_error
    render status: 500
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Controller home boards
class HomeController < ApplicationController
  def index; end

  def show; end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

# Controller lists
class ListsController < ApplicationController
  before_action :list_params_json, only: %i[create]
  before_action :list, only: %i[update destroy]
  before_action :list_params, only: %i[update]

  def create
    @list = List.new(@list_send)
    if @list.save
      message_redirect_type('success', 'create', 'back', 'list')
    else
      message_redirect_type('danger', 'create', 'back', 'list')
    end
  end

  def update
    if @list.update(@list_send)
      message_redirect_type('success', 'update', 'back', 'list')
    else
      message_redirect_type('danger', 'update',  'back', 'list')
    end
  end

  def destroy
    if @list.destroy
      message_redirect_type('success', 'remove', 'back', 'list')
    else
      message_redirect_type('danger', 'remove', 'back', 'list')
    end
  end

  private

  def list
    @list = params[:list_id].present? ? List.find(params[:list_id]) : List.find(params[:list_id_del])
  end

  def list_params
    @list_send = params.permit(:list_title)
    @list_send['title'] = @list_send.delete('list_title')
  end

  def list_params_json
    @list_send = JSON.parse(params[:list_new]).with_indifferent_access
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
# frozen_string_literal: true

# List all cards for lists in board
module CardsHelper
  def all_cards_for_lists
    @all_cards = @list.cards
  end
end

app/views/boards/index.html.erb
<div class="container">
<div class="header"><%= t 'field.my', value: (t 'controller.board') %></div>
  
  <% @boards.each do |board| %>
    <div class="box">
      <%= link_to board.title, board_path(board), class:"flex success" %>
    </div>
  <% end %>
  
  <div class="box success">
    <%= link_to (t 'messages.project.add', value: (t 'controller.board')), boards_path, class:"flex success", data: {toggle: "modal", target: "#modal_board"} %>
  </div>
</div>

app/views/boards/show.html.erb
<%= render 'partial/list' %>
<%= render 'partial/card' %>
<%= render 'partial/card_new' %>
<%= javascript_include_tag "modal_list_autocomplete" %>
<%= javascript_include_tag "modal_card_autocomplete" %>

<div class="bord-nav">
  <div class="left bord-header"><%= @board.title %></div>
  <div class="left bord-header"><%= @board.description %></div>
  <div class="right">
    <a data-toggle="modal" data-target="#modal_board" class="btn btn-light"><i class="fa fa-cog"></i></a>
    <%= link_to root_path , class: "btn btn-danger" do %><i class="fas fa-door-open"></i><% end %>
  </div>
</div>
<div class="bord-lists">
  <% @all_lists_for_board.each_with_index do |list, list_index| %>
    <% @list = list %>
    <% all_cards_for_lists %>
    <div class="list_container">
      <small class="pad-list-header"><%= list.title %></small>
      <a data-toggle="modal" data-target="#modal_list" data-list-id="<%= list.id %>" data-list-title="<%= list.title %>" 
        data-board-id="<%= @board.id %>" class="btn btn-light right"><i class="fa fa-cog"></i></a>
      <ul id="ul<%= list_index %>" list="<%= @list.id %>" ondrop="drop(event)" ondragover="allowDrop(event)">
        <% @all_cards.each_with_index do |card, card_index| %>
            <li id="ul<%= list_index %>li<%= card_index %>" name="<%= @list.id %>" card="<%= card.id %>" 
            draggable="true" ondragstart="drag(event)" data-toggle="modal" href="#modal_card" data-target="#modal_card" 
            data-list-id="<%= list.id %>" data-card-id="<%= card.id %>" data-card-title="<%= card.title %>" 
            data-card-description="<%= card.description %>">
              <%= card.title %>
            </li>
        <%end%>
      </ul>
      <div class="new-card" data-toggle="modal" data-list-id="<%= list.id %>" data-target="#modal_card_new">Novo item</div>
    </div>
  <% end %>
  <div class="list_container">
    <small class="pad-list-header"><%= (t 'messages.project.add', value: (t 'controller.list').downcase) %></small>
    <%= text_field_tag :list_new , nil, type: 'text', maxlength: 16, class: 'form-control new-list' , autocomplete: :off, required: true %>
    <%= hidden_field_tag :board_id, @board.id %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "project.title" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="<%= @bg %>">
    <%= render 'partial/messages' %>
    <%= render 'partial/board' %>
    <%= yield %>
  </body>
</html>

app/views/partial/_board.html.erb
<div class="modal fade" id="modal_board" tabindex="-1" role="dialog" aria-labelledby="modal_board" aria-hidden="true">
  <div class="modal-dialog modal-ml" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          <%= t 'messages.project.add', value: (t 'controller.board').downcase %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag({controller: "boards", action: @action }, method: @method, id: 'form_board') do %>
          <div class="form-group">
            <small><%= t "field.title", value: (t 'controller.board') %></small>
            <%= text_field_tag :title , @title, type: 'text', class: 'form-control' , autocomplete: :off, required: true %>
          </div>
          <div class="form-group">
            <small><%= t "field.description", value: (t 'controller.board') %></small>
            <%= text_area_tag :description , @description , rows: 2, cols: 50, maxlength: 75 , class: 'form-control' %>
          </div>
            <span><%= button_tag (t 'field.save'), class: "btn btn-block btn-success" %></span>
        <% end %>
        <% if @action == "update" %>
          <%= form_tag({controller: "boards", action: "destroy" }, method: "delete") do %>
            <%= hidden_field_tag "id", @board.id %>
            <%= button_tag (t 'field.del'), class: "btn btn-danger btn-block mt-1" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/partial/_card.html.erb
<div class="modal fade" id="modal_card" tabindex="-1" role="dialog" aria-labelledby="modal_card" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          <%= t 'messages.project.add', value: (t 'controller.card') %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag({controller: "cards", action:  "update" }, method: "patch") do %>
          <div class="form-row">
            <div class="form-group col-md-12">
              <small class="margin01"><%= t "field.title", value: (t 'controller.card') %></small>
              <span><%= text_field_tag :title , nil , maxlength: 20 , class: 'form-control' , autocomplete: :off, required: true %></span>
              <small class="margin01"><%= t "field.description", value: (t 'controller.card') %></small>
              <%= text_field_tag :description , nil , maxlength: 120 , class: 'form-control' , autocomplete: :off %>
              <small class="margin01"><%= t "field.list", value: (t 'controller.card') %></small>
              <%= collection_select( :list, :list_id, @all_lists_for_board,:id , :title ,{selected: ""}, {id: "list_id", name: "list_id", class: "form-control" , required: true } ) %>
              <%= hidden_field_tag :card_id %>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-12">
              <%= button_tag (t 'field.save'), class: "btn btn-block btn-success mb-1" %>
        <% end %>
            <%= form_tag({controller: "cards", action: "destroy" }, method: "delete") do %>
              <%= hidden_field_tag "card_id_del" %>
              <%= button_tag (t 'field.del'), class: "btn btn-danger btn-block" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partial/_card_new.html.erb
<div class="modal fade" id="modal_card_new" tabindex="-1" role="dialog" aria-labelledby="modal_card_new"
  aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          <%= t 'messages.project.add', value: (t 'controller.card') %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag({controller: "cards", action: "create" }, method: "post") do %>
          <div class="form-row">
            <div class="form-group">
              <small class="margin01"><%= t "field.title", value: (t 'controller.card') %></small>
              <span><%= text_field_tag :title , nil , maxlength: 20 , class: 'form-control' , autocomplete: :off, required: true %></span>
              <small class="margin01"><%= t "field.description", value: (t 'controller.card') %></small>
              <%= text_field_tag :description , nil , maxlength: 120 , class: 'form-control' , autocomplete: :off %>
              <%= hidden_field_tag :list_id %>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-12">
              <%= button_tag (t 'field.save'), class: "btn btn-block btn-success" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/partial/_list.html.erb
<div class="modal fade" id="modal_list" tabindex="-1" role="dialog" aria-labelledby="modal_list" aria-hidden="true">
  <div class="modal-dialog modal-ml" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          <%= t 'messages.project.add', value: (t 'controller.list').downcase %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag({controller: "lists", action: 'update' }, method: 'patch', id: 'form_list') do %>
          <div class="form-group">
            <small><%= t "field.title", value: (t 'controller.list') %></small>
            <%= text_field_tag :list_title , nil, maxlength: 16, type: 'text', class: 'form-control', autocomplete: :off, required: true %>
            <%= hidden_field_tag :list_id %>
          </div>
            <span><%= button_tag (t 'field.save'), class: "btn btn-block btn-success" %></span>
        <% end %>
        <%= form_tag({controller: "lists", action: "destroy" }, method: "delete") do %>
          <%= hidden_field_tag :list_id_del %>
          <%= button_tag (t 'field.del'), class: "btn btn-danger btn-block mt-1" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/partial/_messages.html.erb
<div class="container-fluid position-absolute fixed-top up-and-down">
	<div class="row">
		<div class="col-sm-10 offset-sm-1">
			<% flash.each do |name, msg| %>
				<div class='alert alert-<%= "#{name}" %>'>
					<%= content_tag :div, 'X', class: 'close', data: {dismiss: 'alert'} %>
					<%= content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String) %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(".alert").delay(4000).fadeOut();
</script>

app/views/partial/messages.html.erb
<div class="container position-absolute fixed-top up-and-down">
	<div class="row">
		<div class="col-sm-10 offset-sm-1">
			<% flash.each do |name, msg| %>
				<div class='alert alert-<%= "#{name}" %>'>
					<a href="#" class="close" data-dismiss="alert">&#215;</a>
					<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(".alert").delay(10000).fadeOut();
</script>